import React from 'react';

const RecentsTrades = () => (
  <div className="trades__main">
    <div className="trades__title">
      <h1>Real-Time</h1>
    </div>
    <div className="table_content">
      <table className="trades__table">
        <thead>
          <tr>
            <th>
              Time
            </th>
            <th>
              Amount
            </th>
            <th>
              Price
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
          <tr>
            <td>
              14:54:50
            </td>
            <td>
              0.020215
            </td>
            <td>
              11740.000
            </td>
          </tr>
        </tbody>

      </table>
    </div>

  </div>
);

export default RecentsTrades;